stages:
  - build
  - test

build-job:
  stage: build
  image: golang:1.17.2
  script:
    - echo "Building cosmzone ..."
    - export GOSUMDB=off
    - go env
    - go clean -modcache
    - make build

test-job-empty:
  stage: test
  script:
    - echo "Tests none yet!"
