include: '.cicd/go-cache.yml'
variables:
  CI_REGISTRY: "public.ecr.aws"
  CI_REGISTRY_USER: "AWS"
  CI_REGISTRY_PASSWORD: ""

stages:
  - prep
  - build
  - test

prep-registry-cred:
  stage: prep
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecr-public get-login-password --region us-east-1

prep-builder-job:
  stage: prep
  needs: ["prep-registry-cred"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG

build-job:
  stage: build
  #image: golang:1.17.2
  extends: .go-cache
  script:
    - echo "Building cosmzone ..."
    - make build_local

test-job-empty:
  stage: test
  script:
    - echo "Tests none yet!"
