include: '.cicd/go-cache.yml'

stages:
  - build
  - test

build-job:
  stage: build
  #image: golang:1.17.2
  extends: .go-cache
  script:
    - echo "Building cosmzone ..."
    - make build_local

test-job-empty:
  stage: test
  script:
    - echo "Tests none yet!"
