include: '.cicd/go-cache.yml'
stages:
  - prep
  - build
  - test

#needs an already configured AWS user on the host system, e.g. `aws configure`
# prep-registry-cred:
#   stage: prep
#   image: amazon/aws-cli
#   variables:
#     CI_REGISTRY: "public.ecr.aws"
#     CI_REGISTRY_USER: "AWS"
#   script:
#     - CI_REGISTRY_PASSWORD=$(aws ecr-public get-login-password --region us-east-1)
#     - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#   cache:


#ref: https://github.com/GoogleContainerTools/kaniko
prep-builder-job:
  stage: prep
  # needs: ["prep-registry-cred"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - export
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

build-job:
  stage: build
  #image: golang:1.17.2
  extends: .go-cache
  script:
    - echo "Building cosmzone ..."
    - make build_local

test-job-empty:
  stage: test
  script:
    - echo "Tests none yet!"
