name: Build
# Builds new binary and creates release draft.
# A version is denoted with a protected tag.
on:
  push:
    # Only tags which match the protected tag pattern will trigger this workflow
    tags:
      - v*.*.*

env:
  VERSION_TAG: ${{ github.ref_name }}
  ARTIFACT_BIN: "nolus.tar.gz"

jobs:
  # Builds new version of the binary.
  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    container:
      image: "public.ecr.aws/nolus/builder:0.7"

    steps:
    - uses: actions/checkout@v3

    # This is to fix GIT not liking owner of the checkout dir
    # Happens when executing not into the default container
    - name: Set ownership
      run: |
        chown -R $(id -u):$(id -g) $PWD

    - name: Run build binary
      run: |
        make build
        echo "Ensuring binary is statically linked ..."
        file target/release/nolusd | grep "statically linked"
        
    - name: Prepare binary tar
      run: |
        tar -C target/release/ -czvf $ARTIFACT_BIN .

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: nolusd-${{ env.VERSION_TAG }}
        path: ${{ env.ARTIFACT_BIN }}

  # Drafts a release
  release:
    name: Draft release
    runs-on: ubuntu-latest
    needs: build-binary
    permissions: write-all

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      # temporary using commit as version until it is merged. Updates node version v12 -> v16
      - uses: "marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            nolusd-${{ env.VERSION_TAG }}
